"""Agent 只读 tool 包装层（G3 · registry + scope + tools）。"""

from app.services.agent.tools.get_chunk_excerpt import (
    NOT_FOUND_SUMMARY,
    GetChunkExcerptOutput,
    GetChunkExcerptToolResult,
    build_result_summary as build_chunk_excerpt_summary,
    run_get_chunk_excerpt,
)
from app.services.agent.tools.list_knowledge_bases import (
    AGENT_MAX_LIMIT,
    ListKnowledgeBasesItem,
    ListKnowledgeBasesOutput,
    ListKnowledgeBasesToolResult,
    build_result_summary,
    build_scope_label,
    normalize_agent_limit,
    run_list_knowledge_bases,
)
from app.services.agent.tools.search_documents import (
    DEFAULT_MODE,
    SearchDocumentsItem,
    SearchDocumentsOutput,
    SearchDocumentsToolResult,
    SearchMode,
    build_result_summary as build_search_documents_summary,
    normalize_mode,
    run_search_documents,
)
from app.services.agent.tools.semantic_search import (
    AGENT_DEFAULT_TOP_K,
    AGENT_MAX_TOP_K,
    SemanticSearchHit,
    SemanticSearchOutput,
    SemanticSearchToolResult,
    build_result_summary as build_semantic_search_summary,
    normalize_top_k,
    run_semantic_search,
)
from app.services.agent.tools.generate_faq_draft import (
    BAD_FILENAME_SUMMARY,
    NO_BASIS_SUMMARY,
    GenerateFaqDraftFailure,
    GenerateFaqDraftOutput,
    GenerateFaqDraftToolResult,
    run_generate_faq_draft,
)
from app.services.agent.tools.registry import (
    ALL_AGENT_TOOL_NAMES,
    READ_ONLY_TOOL_NAMES,
    AgentToolName,
    ReadOnlyToolName,
    UnknownToolError,
    is_allowed_tool,
    is_known_agent_tool,
    parse_agent_tool,
    parse_allowed_tool,
)
from app.services.agent.tools.scope import (
    FORBIDDEN_KB_SUMMARY,
    AgentToolScope,
    KbScope,
    ToolDenial,
    ToolDenialReason,
)

__all__ = [
    "BAD_FILENAME_SUMMARY",
    "NO_BASIS_SUMMARY",
    "AGENT_DEFAULT_TOP_K",
    "AGENT_MAX_LIMIT",
    "AGENT_MAX_TOP_K",
    "ALL_AGENT_TOOL_NAMES",
    "FORBIDDEN_KB_SUMMARY",
    "NOT_FOUND_SUMMARY",
    "READ_ONLY_TOOL_NAMES",
    "AgentToolName",
    "AgentToolScope",
    "GenerateFaqDraftFailure",
    "GenerateFaqDraftOutput",
    "GenerateFaqDraftToolResult",
    "GetChunkExcerptOutput",
    "GetChunkExcerptToolResult",
    "KbScope",
    "ListKnowledgeBasesItem",
    "ListKnowledgeBasesOutput",
    "ListKnowledgeBasesToolResult",
    "ReadOnlyToolName",
    "DEFAULT_MODE",
    "SearchDocumentsItem",
    "SearchDocumentsOutput",
    "SearchDocumentsToolResult",
    "SearchMode",
    "SemanticSearchHit",
    "SemanticSearchOutput",
    "SemanticSearchToolResult",
    "ToolDenial",
    "ToolDenialReason",
    "UnknownToolError",
    "build_result_summary",
    "build_scope_label",
    "build_chunk_excerpt_summary",
    "build_search_documents_summary",
    "build_semantic_search_summary",
    "is_allowed_tool",
    "is_known_agent_tool",
    "normalize_mode",
    "normalize_agent_limit",
    "normalize_top_k",
    "parse_agent_tool",
    "parse_allowed_tool",
    "run_get_chunk_excerpt",
    "run_generate_faq_draft",
    "run_list_knowledge_bases",
    "run_search_documents",
    "run_semantic_search",
]
